---
title: Useful List Functions
---

As you have seen, Python lists are extremely useful data structures. In the first Python lesson, you were introduced to several list functions that, for example, reverse a list, sort a list, etc. In this lesson, we will cover several more powerful built-in functions that are quite useful when used with lists.

## Filter

The `filter` function returns an **iterator** that contains a new list consisting of only the items within an existing list for which some user-defined function is true. The user-defined function can be anything that evaluates an input in the existing list and returns `True` or `False`. The format for the `filter` function is as follows:

```Python
def my_func(data):
    """A function that returns True or False"""
    # implementation omitted

filter(my_func, my_list)
```

The parameter `my_func` represents the name of the function that will evaluate each item in the existing list. The parameter `my_list` is, of course, the existing list of items to evaluate. 

An **iterator** is an object that contains a list. We can use iterators to operate on a list of values. To convert this iterator into a list object, that would expose the list it contains, we should wrap the call to filter with a list constructor:

```python
list(filter(my_func, my_list))
```

This converts the returned iterator into a list that we can print directly.

Suppose, for example, that you want to find all of the multiples of three or five that are less than or equal to 30 and make a list of them. 

Here is one way to do it with by utilizing a `for` loop:

```python
# for loop 
multiples = []

for i in range(3, 31):
    if (i % 3 == 0 or i % 5 == 0):
        multiples.append(i)
```

However, here's how it could be done with the `filter` function:

```python
def is_multiple(x):
    return (x % 3 == 0 or x % 5 == 0)

multiples = list(filter(is_multiple, range(3, 31)))
```

Both of these methods generate the following list:

```python
[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30]
```

## Map

The `map` function returns an **iterator** that contains a new list consisting of the return values generated by a user-defined function on each item in an existing list. The user-defined function is called for each item in the existing list; the return values form the new list. The format for the `map` function is as follows:

```python
def my_func(data):
    """A function that returns"""
    # Note that this function does not need to return
    # True or False like the one for filter did.

map(my_func, my_list)
```

Like the `filter` function, we need to wrap the call to `map` inside of a list constructor call:

```python
list(map(my_func, my_list))
```

The parameters are the same as specified for the `filter` function. Suppose, for example, that you want to square each item in a list. 

Here's one way to do this by using a for loop:

```python
squares = list(range(1, 10))

for i in range(len(squares)):
    squares[i] *= squares[i]
```

Although the snippet of code above does modify the existing list, it could be easily changed if needed. Here's how it could be done with the `map` function:

```python
def square(x):
    return x * x

squares = list(map(square, range(1, 10)))
```

Both methods produce the following list:

```python
[1, 4, 9, 16, 25, 36, 49, 64, 81]
```

## Reduce

Lastly, the `reduce` function processes the elements in a list through a user-defined function and returns a single value. The function works by first processing the first two items of the list. The result of this is processed by the function, along with the next item in the list. This continues for all of the remaining items in the list. The format for the `reduce` function is as follows:

```python
def my_func(data1, data2):
    """A function that operates on data1 and data2"""
    # Note that this function takes 2 arguments

reduce(my_func, list)
```

Again, the parameters are the same as specified for the previous functions. Suppose, for example, that you want to compute the factorial of 10. 

Here's one way to do this by using a `for` loop:

```python
fact = 1
for i in range(1, 11):
    fact *= i
```

Finally, here's how to do it with the `reduce` function. Note that the `reduce` function comes from the `functools` module that is part of Python. This means we need to import the function from that module before we can use it:

```python
from functools import reduce

def multiply(x, y):
    return x * y

fact = reduce(multiply, range(1, 11))
```

Both methods calculate the factorial of 10 (which is 3628800).

## Summary

The following table summarizes the list functions discussed above:

|Function  |Purpose    | Syntax    | Returns |
|:---      |:--------- |:--------- | :---    |
| `filter` | Select list elements using a function that returns a Boolean value  | `filter(function, list)` | iterator |
| `map`    | Apply a function to every list element             | `map(function, list)`    | iterator |
| `reduce` | Reduce a list to a single value using a function   | `reduce(function, list)` | value    |


## Knowledge Check

**1.** What type of object does the `filter` function return?

- A) A list
- B) A single value
- C) An iterator
- D) A dictionary

::: {.callout-note collapse="true" title="Answer"}
**C) An iterator.** To get a list, you must wrap the call with the `list()` constructor: `list(filter(...))`.
:::

---

**2.** Which of the following best describes what `map` does?

- A) Selects only the elements for which a condition is `True`
- B) Applies a function to every element in a list and returns the results
- C) Reduces a list down to a single value
- D) Sorts the elements of a list

::: {.callout-note collapse="true" title="Answer"}
**B) Applies a function to every element in a list and returns the results.** Option A describes `filter`, and option C describes `reduce`.
:::

---

**3.** What does the following code produce?

```python
def double(x):
    return x * 2

result = list(map(double, [1, 2, 3, 4]))
```

- A) `[1, 4, 9, 16]`
- B) `20`
- C) `[2, 4, 6, 8]`
- D) `[1, 2, 3, 4]`

::: {.callout-note collapse="true" title="Answer"}
**C) `[2, 4, 6, 8]`.** `map` applies `double` to each element, so every value is multiplied by 2.
:::

---

**4.** Unlike `filter` and `map`, what does `reduce` return?

- A) An iterator
- B) A list
- C) A boolean
- D) A single value

::: {.callout-note collapse="true" title="Answer"}
**D) A single value.** `reduce` accumulates the result by repeatedly applying a two-argument function across the list until one value remains.
:::

---

**5.** What does the following code produce?

```python
def is_even(x):
    return x % 2 == 0

result = list(filter(is_even, [1, 2, 3, 4, 5, 6]))
```

- A) `[1, 3, 5]`
- B) `[1, 2, 3, 4, 5, 6]`
- C) `[2, 4, 6]`
- D) `12`

::: {.callout-note collapse="true" title="Answer"}
**C) `[2, 4, 6]`.** `filter` keeps only the elements for which `is_even` returns `True`, which are the even numbers 2, 4, and 6.
:::
