---
title: IEEE 754 Floating Point Representation
---

IEEE 754 is a set of standards that describe how floating point values should be represented at the machine level. This page contains a summary of how this is done for 32-bit values that are not very close to 0, that is, **normalized form**. 


## General Information

As a binary value, there are 3 fields that form an IEEE 754 formated number: 

- The sign field 

- The exponent field

- The mantissa field

The **sign field** is 1 bit, while the other two fields vary depending on the precision of the value. A 16-bit number is referred to as a **half-precision** value, a 32-bit number is a **single precision** value, and a 64-bit number is a **double precision** value. An example of a single precision value follows in the text field below.

```text
11000000100010000000000000000000
```

The same single precision value can be split into its different fields as follows for human readability purposes.

```text
Sign Field    Exponent Field    Mantissa Field
-----------   ---------------   ----------------------------
1             1000 0001         0001 0000 0000 0000 0000 000
```

While Python does not distinguish single precision from double precision for the user, other languages such as the C language do. A float in the C language is 32-bit single precision value while a double are 64-bit double precision values. The number of bits in each field for single and double precision values is indicated in the table that follows.

| Precision | Sign Bits | Exponent Bits | Mantissa Bits |
|-----------|-----------|---------------|---------------|
| Single    | 1         | 8             | 23            |
| Double    | 1         | 11            | 52            |


When representing floating point values, there are three cases of this standard that are considered:

1. Normalized Form

    - The "common" case.

    - Used to represent values that are not very close to 0. 

    - Examples would include `1.98` or `-11.2345`

2. Denormalized Form

    - Used to represent 0 and values very close to 0.

    - An example would be $1.18 \times 10 ^ {-38}$

3. Special values

    - Used for special numbers like $+\infty$ and $-\infty$


In this course, we are only concerned with the normalized form as this is used to represent the most common numbers.


## Normalized Form

This is the common case. Some key features of this form include:

- The exponent field is not all 0s.

- The exponent field is not all 1s.

- The exponent field is biased in some way. 

    * For 32-bit values the bias is 127

    * For 64-bit values, the bias is 1023

- The mantissa field will represent a fractional value $x$ with an understood `1.` in front of it. That is, if we have a value $1.0110$, then the mantissa field is everything after the radix point (i.e. $0110$)

## Base 10 to IEEE 754

### Example 1

Convert -4.25 to single precision IEEE 754 floating point number (i.e. 32-bits).


1. **Convert base number (ignoring sign) to binary**

    **Whole Part:**

    
    Whole part is 4. Divide quotients by 2 repeatedly and read the remainders in reverse order to get the binary value.
 
    ```
        4 / 2 = 2r0
        2 / 2 = 1r0
        1 / 2 = 0r1    // stop when quotient is 0
    ```
    Reading the remainders in reverse gives $100$.
    

    **Fractional Part:**


    Fractional Part is 0.25. Multiply the fractional parts by 2 repeatedly and read the whole parts from the top down.

    ```
                   Whole part
                   |
                   | Fractional Part
                   | |  
                   v v
        0.25 * 2 = 0.5
        0.5  * 2 = 1.0  // stop when fractional part is 0
    ```

    Reading the whole parts from top down gives $01$.

    **Recombine**

    Finish this step by combining the whole and fractional binary results into $100.01$

2. **Implicitly Normalize the Previous Result**

   Shift the radix point (decimal point) to the right of the most significant bit. This shift is done by multiplying your binary value by $2^k$ where $k$ is the number of place values you need to shift your radix point.

   ```
        100.01 
        10.001   // shifted left one place
        1.0001   // shifted left 2 places total. stop here.
   ```

   **Identify the True Exponent**

   The exponent is $2$ since we shifted $2$ places to the left.
   We will refer to this exponent as the `TrueExponent`. Recall that the exponent field holds a `BiasedExponent` instead of the `TrueExponent`.

   **Identify the Mantissa Field**

   The mantissa field will start with $0001$ since that is the value to the right of the radix point.
   *Do not discard leading 0s in the mantissa*. The leading 0s are important. We can (and will), however, place trailing 0s after this value.



3. **Bias the Exponent**

    Apply a bias to your `TrueExponent` value. Since we are working under single precision (32-bit), our bias is 127.
    
    $$ 
    \begin{aligned}
    \text{BiasedExponent} &= \text{TrueExponent} + 127\\
    \text{BiasedExponent} &= 2 + 127\\
    \text{BiasedExponent} &= 129\\
    \end{aligned}
    $$

4. **Convert the Biased Exponent to Binary**

    The exponent is represented using 8 bits in single precision.

    Using the subtraction method:

    $$
    \begin{aligned}
    129 - 2^7 &= 1\\
    1 - 2^0 &= 0\\
    \end{aligned}
    $$

    So our binary representation is $1000 0001$. Thus our exponent field is `1000 0001`

5. **Put it all together**

    In the previous steps, we saw: 

    - Sign is -, thus the sign field is 1.
    
    - The exponent field was `1000 0001` 
    
    - The mantissa field was `0001`.

    Placing each value into their respective fields and adding trailing 0s to the mantissa give the following result.

    ```
    Final Result:
    S    Exponent    Mantissa (23 bits total)
    --   ----------  ----------------------------
    1    1000 0001   0001 0000 0000 0000 0000 000
    ```

    Note that we placed spaces after every 4 bits for readability. The true result would be: `11000000100010000000000000000000`.


### Example 2

Convert +13.625 to a single precision IEEE 754 floating point number (i.e. 32-bits).


1. **Convert base number (ignoring sign) to binary**

    **Whole Part:**

    Whole part is 13. Divide quotients by 2 repeatedly and read the remainders in reverse order to get the binary value.

    ```
        13 / 2 = 6r1
        6  / 2 = 3r0
        3  / 2 = 1r1
        1  / 2 = 0r1    // stop when quotient is 0
    ```
    Reading the remainders in reverse gives $1101$.

    **Fractional Part:**

    Fractional part is 0.625. Multiply the fractional parts by 2 repeatedly and read the whole parts from the top down.

    ```
                    Whole part
                    |
                    | Fractional Part
                    | |
                    v v
        0.625 * 2 = 1.25
        0.25  * 2 = 0.5
        0.5   * 2 = 1.0  // stop when fractional part is 0
    ```

    Reading the whole parts from top down gives $101$.

    **Recombine**

    Finish this step by combining the whole and fractional binary results into $1101.101$.

2. **Implicitly Normalize the Previous Result**

   Shift the radix point to the right of the most significant bit by multiplying by $2^k$ where $k$ is the number of places shifted.

   ```
        1101.101
        110.1101   // shifted left one place
        11.01101   // shifted left 2 places
        1.101101   // shifted left 3 places total. stop here.
   ```

   **Identify the True Exponent**

   The exponent is $3$ since we shifted $3$ places to the left.
   We will refer to this exponent as the `TrueExponent`.

   **Identify the Mantissa Field**

   The mantissa field will start with $101101$ since that is the value to the right of the radix point.
   *Do not discard leading 0s in the mantissa*. We can (and will) place trailing 0s after this value.

3. **Bias the Exponent**

    Apply a bias to your `TrueExponent` value. Since we are working under single precision (32-bit), our bias is 127.

    $$
    \begin{aligned}
    \text{BiasedExponent} &= \text{TrueExponent} + 127\\
    \text{BiasedExponent} &= 3 + 127\\
    \text{BiasedExponent} &= 130\\
    \end{aligned}
    $$

4. **Convert the Biased Exponent to Binary**

    The exponent is represented using 8 bits in single precision.

    Using the subtraction method:

    $$
    \begin{aligned}
    130 - 2^7 &= 2\\
    2 - 2^1 &= 0\\
    \end{aligned}
    $$

    So our binary representation is $1000\ 0010$. Thus our exponent field is `1000 0010`.

5. **Put it all together**

    In the previous steps, we saw:

    - Sign is +, thus the sign field is 0.

    - The exponent field was `1000 0010`

    - The mantissa field was `101101`.

    Placing each value into their respective fields and adding trailing 0s to the mantissa give the following result.

    ```
    Final Result:
    S    Exponent    Mantissa (23 bits total)
    --   ----------  ----------------------------
    0    1000 0010   1011 0100 0000 0000 0000 000
    ```

    Note that we placed spaces after every 4 bits for readability. The true result would be: `01000001010110100000000000000000`.

## IEEE 754 to Base 10

### Example 3

Convert the following 32-bit IEEE 754 normalized form value to decimal.

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
0    1000 0011   1000 1100 0000 0000 0000 000
```


1. **Convert the Exponent to Decimal** 

   Convert the exponent to decimal by multiplying by the appropriate powers of two and adding the sums.

   ```
         1    0   0   0   0   0   1   1
    x  128   64  32  16   8   4   2   1 
    ------------------------------------
       128 +  0 + 0 + 0 + 0 + 0 + 2 + 1  = 131
   ```

2. **Unbias the Exponent**

    Recall the exponent field holds a biased exponent, thus we need to unbias it. For 32-bit values, the bias is 127. We subtract 127 from the biased exponent. 

    $$
    \begin{align}
    \text{TrueExponent} &= \text{BiasedExponent} - 127\\
    \text{TrueExponent} &= 131 - 127\\
    \text{TrueExponent} &= 4\\
    \end{align}
    $$

3. **Use the Formula to Express the Value as Fractional Binary**

    We can use the following formula where $MF$ is the mantissa field, $TE$ is the true exponent, and $S$ is the sign to get a fractional binary form.

    $$(-1)^S \times 1.MF \times 2^{TE}$$

    Recall that the mantissa field is `1000 11` without the trailing 0s.

    We get the following:

    $$(-1)^0 \times 1.100011 \times 2^{4}$$

    Simplifying this expressing gives $11000.11$ as a fractional binary expression.

4. **Convert the Fractional Binary Expression to Base 10**

    Convert the fractional binary expression $11000.11$ to decimal by multiplying by the appropriate powers of two and adding the sums.

   ```
          1   1   0   0   0 .   1     1
    x    16   8   4   2   1   0.5  0.25
    ------------------------------------
        16 +  8 + 0 + 0 + 0 + 0.5 + 0.25  = 24.75
   ```

   The value is $24.75$ in base 10.


### Example 4

Convert the following 32-bit IEEE 754 normalized form value to decimal.

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
1    1000 0011   0011 1000 0000 0000 0000 000
```


1. **Convert the Exponent to Decimal**

   Convert the exponent to decimal by multiplying by the appropriate powers of two and adding the sums.

   ```
         1    0   0   0   0   0   1   1
    x  128   64  32  16   8   4   2   1
    ------------------------------------
       128 +  0 + 0 + 0 + 0 + 0 + 2 + 1  = 131
   ```

2. **Unbias the Exponent**

    Recall the exponent field holds a biased exponent, thus we need to unbias it. For 32-bit values, the bias is 127. We subtract 127 from the biased exponent.

    $$
    \begin{align}
    \text{TrueExponent} &= \text{BiasedExponent} - 127\\
    \text{TrueExponent} &= 131 - 127\\
    \text{TrueExponent} &= 4\\
    \end{align}
    $$

3. **Use the Formula to Express the Value as Fractional Binary**

    We can use the following formula where $MF$ is the mantissa field, $TE$ is the true exponent, and $S$ is the sign to get a fractional binary form.

    $$(-1)^S \times 1.MF \times 2^{TE}$$

    Recall that the mantissa field is `00111` without the trailing 0s.

    We get the following:

    $$(-1)^1 \times 1.00111 \times 2^{4}$$

    Simplifying this expression gives $-10011.1$ as a fractional binary expression.

4. **Convert the Fractional Binary Expression to Base 10**

    Convert the fractional binary expression $10011.1$ to decimal by multiplying by the appropriate powers of two and adding the sums.

   ```
          1   0   0   1   1 .   1
    x    16   8   4   2   1   0.5
    --------------------------------
        16 +  0 + 0 + 2 + 1 + 0.5  = 19.5
   ```

   Applying the negative sign from step 3, the value is $-19.5$ in base 10.

## Knowledge Check

Convert the following base 10 values to single precision IEEE 754.

**1.** $-7.5$

::: {.callout-note collapse="true"}
## Answer

**Step 1 — Convert to binary**

Whole part (7): `7/2=3r1`, `3/2=1r1`, `1/2=0r1` → $111$

Fractional part (0.5): `0.5×2=1.0` → $1$

Combined: $111.1$

**Step 2 — Normalize**

```
111.1
11.11   // shifted left 1
1.111   // shifted left 2 total → TrueExponent = 2, Mantissa = 111
```

**Step 3 — Bias the exponent**

$$\text{BiasedExponent} = 2 + 127 = 129$$

**Step 4 — Convert biased exponent to binary**

$$129 - 2^7 = 1, \quad 1 - 2^0 = 0 \implies 1000\ 0001$$

**Step 5 — Final result**

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
1    1000 0001   1110 0000 0000 0000 0000 000
```

True result: `11000000111100000000000000000000`
:::

**2.** $+22.375$

::: {.callout-note collapse="true"}
## Answer

**Step 1 — Convert to binary**

Whole part (22): `22/2=11r0`, `11/2=5r1`, `5/2=2r1`, `2/2=1r0`, `1/2=0r1` → $10110$

Fractional part (0.375):
```
0.375 × 2 = 0.75  → 0
0.75  × 2 = 1.5   → 1
0.5   × 2 = 1.0   → 1  (stop)
```
Fractional binary: $011$

Combined: $10110.011$

**Step 2 — Normalize**

```
10110.011
1.0110011   // shifted left 4 total → TrueExponent = 4, Mantissa = 0110011
```

**Step 3 — Bias the exponent**

$$\text{BiasedExponent} = 4 + 127 = 131$$

**Step 4 — Convert biased exponent to binary**

$$131 - 2^7 = 3, \quad 3 - 2^1 = 1, \quad 1 - 2^0 = 0 \implies 1000\ 0011$$

**Step 5 — Final result**

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
0    1000 0011   0110 0110 0000 0000 0000 000
```

True result: `01000001101100110000000000000000`
:::

Convert the following single precision IEEE 754 values to base 10.

**3.**

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
0    1000 0010   1100 0000 0000 0000 0000 000
```

::: {.callout-note collapse="true"}
## Answer

**Step 1 — Convert exponent to decimal**

```
      1   0   0   0   0   0   1   0
x   128  64  32  16   8   4   2   1
------------------------------------
    128 + 0 + 0 + 0 + 0 + 0 + 2 + 0  = 130
```

**Step 2 — Unbias the exponent**

$$\text{TrueExponent} = 130 - 127 = 3$$

**Step 3 — Express as fractional binary**

Mantissa field (dropping trailing 0s): `11`

$$(-1)^0 \times 1.11 \times 2^3 = 1110.0$$

**Step 4 — Convert to base 10**

```
     1   1   1   0
x    8   4   2   1
------------------
     8 + 4 + 2 + 0  = 14
```

The value is $14.0$ in base 10.
:::

**4.**

```
S    Exponent    Mantissa (23 bits total)
--   ----------  ----------------------------
1    0111 1110   0100 0000 0000 0000 0000 000
```

::: {.callout-note collapse="true"}
## Answer

**Step 1 — Convert exponent to decimal**

```
      0   1   1   1   1   1   1   0
x   128  64  32  16   8   4   2   1
------------------------------------
      0 + 64 + 32 + 16 + 8 + 4 + 2 + 0  = 126
```

**Step 2 — Unbias the exponent**

$$\text{TrueExponent} = 126 - 127 = -1$$

**Step 3 — Express as fractional binary**

Mantissa field (dropping trailing 0s): `01`

$$(-1)^1 \times 1.01 \times 2^{-1} = -0.101$$

**Step 4 — Convert to base 10**

```
     0 .  1     0     1
x    1   0.5  0.25  0.125
-------------------------
     0 + 0.5 + 0 + 0.125  = 0.625
```

Applying the negative sign, the value is $-0.625$ in base 10.
:::

For more practice with normalized form, try using the linked [IEEE-754 Floating Point Convert](https://www.h-schmidt.net/FloatConverter/IEEE754.html).
